[package]
name = "z-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rowan = "0.15.11"
m_lexer = "0.0.4"
pest = "2.6"
pest_derive = "2.6"
lazy_static = "1.4.0"
[dev-dependencies]